### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by Damm06** [Damm06/preHomework#2]
### 해당 기능을 구현하기 위해 할 일
1. [ ] 기능/비기능 요구사항 정리
2. [ ] 기능별 상세 내용 적기
3. [ ] 우선순위, 구분 등 모든 항목 채워서 문서화
